package interfete;
/**
 *
 * @author Razvan
 */
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import com.mycompany.magazinelectronice.*;
import newpackage.InterfataGraficaMagazinElectronice;
import java.awt.*;
import java.text.DecimalFormat;
import java.math.RoundingMode;
import newpackage.*;
public class telefoaneint extends javax.swing.JFrame {

    /**
     * Creates new form telefoaneint
     */
        Telefon tel1 = new Telefon();
        Telefon tel2 = new Telefon("Xiaomi","11T","Mediatek MT6893 Dimensity 1200", "AMOLED", "Space Gray", "4G,5G", "Android 14", "Usb C","NanoSim",38,128,12,2021,4,"108 MP Wide, 8 MP Ultrawide, 5 MP Telephoto macro, 16 MP Front", 5000, 1600, 6.67f,"1080 x 2400" );
        Telefon tel3 = new Telefon("Samsung","S23 Ultra","Qualcomm SM8550-AC Snapdragon 8 Gen 2", "Dynamic AMOLED 2x", "Phantom Black", "4G,5G", "Android 14", "Usb C, Wireless, Reverse Wireless","NanoSim",23,512,12,2023,5,"200 MP Wide, 12 MP Ultrawide, 10 MP Telephoto , 10 MP periscope telephoto, 12 MP Front", 5000, 7600, 6.8f,"1440 x 3088");
        Telefon tel4 = new Telefon("Apple","14 Pro Max","Apple 16 Bionic", "LTPO Super Retina XDR OLED", "Gold", "4G,5G", "iOS 17", "Lightning","NanoSim",75,512,10,2022,4,"48 MP Wide, 12 MP Ultrawide, 12 MP Telephoto , 12 MP Front", 4323, 5899, 6.7f,"1290 x 2796");
        Telefon tel5 = new Telefon("Nokia","G42","Qualcomm SM4350-AC Snapdragon 480+ 5G", "IPS LCD", "Purple", "4G,5G", "Android 13", "Usb C","NanoSim",239,64,6,2023,4,"50 MP Wide, 2 MP Ultrawide, 2 MP Telephoto macro, 8 MP Front", 5000, 1399.99f, 6.56f,"720 x 1612");
        Telefon tel6 = new Telefon("Nokia","C300","Qualcomm SM6115 Snapdragon 662", "IPS LCD", "Blue", "4G,5G", "Android 13", "Usb C","NanoSim",8,128,8,2023,4,"13 MP Wide, 2 MP Ultrawide, 2 MP Telephoto macro, 8 MP Front", 4000, 832.78f, 6.52f,"720 x 1600");
        Telefon tel7 = new Telefon("Apple","iPhone 15 Pro Max","Apple A17 Pro", "LTPO Super Retina XDR OLED", "White Titanium", "4G,5G", "iOS 17", "Usb C","NanoSim",2,512,8,2023,4,"48 MP Wide, 12 MP Ultrawide, 12 MP Telephoto macro, 12 MP Front", 4441, 8978.64f, 6.7f,"1290 x 2796");
        Telefon tel8 = new Telefon("Apple","iPhone 15 Plus","Apple A16 Bionic", "Super Retina XDR OLED", "Green", "4G,5G", "iOS 17", "Usb C, Wireless","NanoSim",96,256,8,2023,3,"48 MP Wide, 12 MP Ultrawide, 12 MP Front", 4383, 5763.90f, 6.7f,"1290 x 2796");
        Telefon tel9 = new Telefon("Xiaomi","14 Pro","Qualcomm SM8650-AB Snapdragon 8 Gen 3", "LTPO AMOLED", "Titanium", "4G,5G", "Android 14, HyperOS", "Usb C, Wireless","NanoSim",1,512,16,2023,4,"50 MP Wide, 50 MP Ultrawide, 50 MP Telephoto macro, 32 MP Front", 4880, 6547.32f, 6.73f,"1440 x 3200");
        Telefon tel10 = new Telefon("Samsung","Galaxy A54","Exynos 1380", "Super AMOLED", "Violet", "4G,5G", "Android 13", "Usb C","NanoSim",0,128,8,2023,4,"50 MP Wide, 12 MP Ultrawide,5 MP Telephoto macro, 32 MP Front", 5000, 2599.23f, 6.4f,"1080 x 2340");
        Telefon tel11 = new Telefon("Samsung","Galaxy S23 FE","Qualcomm SM8450 Snapdragon 8 Gen 1", "Dynamic AMOLED 2X", "Mint", "4G,5G", "Android 14", "Usb C","NanoSim",92,256,8,2023,4,"50 MP Wide, 8 MP Ultrawide, 12 MP Telephoto macro, 10 MP Front", 4500, 4599.23f, 6.4f,"1080 x 2340");
        Telefon tel12 = new Telefon(tel2);
        private Telefon[] telefoane = {tel2,tel3,tel4,tel5,tel6,tel7,tel8,tel9,tel10,tel11};
       
    public telefoaneint() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        initializareComboBox(); // Inițializează combobox-ul
        adaugaActionListenerComboBox();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backtest = new java.awt.Button();
        titlu = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        home = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backtest.setBackground(new java.awt.Color(255, 51, 51));
        backtest.setLabel("Back");
        backtest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtestActionPerformed(evt);
            }
        });

        titlu.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        titlu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlu.setText("Telefoane");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apasati pentru a vedea telefoanele" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
                ActionListener(evt);
                ActionEvent(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        menu.setText("Home");
        menu.setToolTipText("");

        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        menu.add(home);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(titlu, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(backtest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backtest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titlu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backtestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtestActionPerformed
        this.setVisible(false);
   
        InterfataGraficaMagazinElectronice home = new InterfataGraficaMagazinElectronice();
        home.setVisible(true);
    }//GEN-LAST:event_backtestActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        this.setVisible(false);
   
        InterfataGraficaMagazinElectronice home = new InterfataGraficaMagazinElectronice();
        home.setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    public void afisarePopUp(int selectedIndex, Telefon[] telefoane){
        
    JFrame popup = new JFrame("Detalii Telefon");
    popup.setSize(1000, 900);
    popup.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    JPanel panel = new JPanel();
    panel.setLayout(new GridLayout(0, 2)); // Layout pentru a afișa perechi etichetă-câmp text
    Telefon selectedPhone = telefoane[selectedIndex];
    
    if (selectedIndex >= 0 && selectedIndex < telefoane.length) {
        JTextField textFieldMarca = new JTextField(selectedPhone.getMarca());
        JTextField textFieldModel = new JTextField(selectedPhone.getModel());
        JTextField textFieldCantitate = new JTextField(String.valueOf(selectedPhone.getCantitate()));
        JTextField textFieldAnAparitie = new JTextField(String.valueOf(selectedPhone.getAnAparitie()));
        JTextField textFieldPret = new JTextField(String.valueOf(selectedPhone.getPret()));
        JTextField textFieldProcesor = new JTextField(selectedPhone.getProcesor());
        JTextField textFieldTipEcran = new JTextField(selectedPhone.getTipEcran());
        JTextField textFieldCuloare = new JTextField(selectedPhone.getCuloare());
        JTextField textFieldFrecventaAntena = new JTextField(selectedPhone.getFrecventaAntena());
        JTextField textFieldSisOpTel = new JTextField(selectedPhone.getSisOpTel());
        JTextField textFieldTipIncarcare = new JTextField(selectedPhone.getTipIncarcare());
        JTextField textFieldTipSim = new JTextField(selectedPhone.getTipSim());
        JTextField textFieldRezEcran = new JTextField(selectedPhone.getRezEcran());
        JTextField textFieldRezCamere = new JTextField(selectedPhone.getRezCamere());
        JTextField textFieldMemorieROM = new JTextField(String.valueOf(selectedPhone.getMemorieROM()));
        JTextField textFieldMemorieRAM = new JTextField(String.valueOf(selectedPhone.getMemorieRAM()));
        JTextField textFieldNrCamere = new JTextField(String.valueOf(selectedPhone.getNrCamere()));
        JTextField textFieldMarimeBat = new JTextField(String.valueOf(selectedPhone.getMarimeBat()));
        JTextField textFieldDiagonalaEcran = new JTextField(String.valueOf(selectedPhone.getDiagonalaEcran()));
    
        addLabelAndTextField(panel, "Marca:", textFieldMarca);
        addLabelAndTextField(panel, "Model:", textFieldModel);
        addLabelAndTextField(panel, "Cantitate:", textFieldCantitate);
        addLabelAndTextField(panel, "An aparitie:", textFieldAnAparitie);
        addLabelAndTextField(panel, "Pret:", textFieldPret);
        addLabelAndTextField(panel, "Procesor:", textFieldProcesor);
        addLabelAndTextField(panel, "Tip ecran:", textFieldTipEcran);
        addLabelAndTextField(panel, "Culoare:", textFieldCuloare);
        addLabelAndTextField(panel, "Frecventa antena:", textFieldFrecventaAntena);
        addLabelAndTextField(panel, "Sistem de operare:", textFieldSisOpTel);
        addLabelAndTextField(panel, "Tip încărcare:", textFieldTipIncarcare);
        addLabelAndTextField(panel, "Tip SIM:", textFieldTipSim);
        addLabelAndTextField(panel, "Rezoluție ecran:", textFieldRezEcran);
        addLabelAndTextField(panel, "Rezoluție camere:", textFieldRezCamere);
        addLabelAndTextField(panel, "Memorie ROM:", textFieldMemorieROM);
        addLabelAndTextField(panel, "Memorie RAM:", textFieldMemorieRAM);
        addLabelAndTextField(panel, "Număr camere:", textFieldNrCamere);
        addLabelAndTextField(panel, "Mărime baterie:", textFieldMarimeBat);
        addLabelAndTextField(panel, "Diagonala ecran:", textFieldDiagonalaEcran);    
        JButton saveButton = new JButton("Salvează");
        saveButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
              String valoareMarca = textFieldMarca.getText();
              String valoareModel = textFieldModel.getText();
              int valoareCantitate =Integer.parseInt (textFieldCantitate.getText());
              int valoareAnAparitie = Integer.parseInt (textFieldAnAparitie.getText());
              float valoarePret = Float.parseFloat(textFieldPret.getText());
              String valoareProcesor = textFieldProcesor.getText();
              String valoareTipEcran = textFieldTipEcran.getText();
              String valoareCuloare = textFieldCuloare.getText();
              String valoareFrecventaAntena = textFieldFrecventaAntena.getText();
              String valoareSisOpTel = textFieldSisOpTel.getText();
              String valoareTipIncarcare = textFieldTipIncarcare.getText();
              String valoareTipSim = textFieldTipSim.getText();
              String valoareRezEcran = textFieldRezEcran.getText();
              String valoareRezCamere = textFieldRezCamere.getText();
              int valoareMemorieROM = Integer.parseInt(textFieldMemorieROM.getText());
              int valoareMemorieRAM = Integer.parseInt(textFieldMemorieRAM.getText());
              int valoareNrCamere = Integer.parseInt(textFieldNrCamere.getText());
              int valoareMarimeBat = Integer.parseInt(textFieldMarimeBat.getText());
              float valoareDiagonalaEcran = Float.parseFloat(textFieldDiagonalaEcran.getText());
              
              selectedPhone.setMarca(valoareMarca);
              selectedPhone.setModel(valoareModel);
              selectedPhone.setCantitate(valoareCantitate);
              selectedPhone.setAnAparitie(valoareAnAparitie);
              selectedPhone.setPret(valoarePret);              
              selectedPhone.setProcesor(valoareProcesor);
              selectedPhone.setTipEcran(valoareTipEcran);
              selectedPhone.setCuloare(valoareCuloare);
              selectedPhone.setFrecventaAntena(valoareFrecventaAntena);
              selectedPhone.setSisOpTel(valoareSisOpTel);
              selectedPhone.setTipIncarcare(valoareTipIncarcare);
              selectedPhone.setTipSim(valoareTipSim);
              selectedPhone.setRezCamere(valoareRezCamere);
              selectedPhone.setMemorieROM(valoareMemorieROM);
              selectedPhone.setRezEcran(valoareRezEcran);
              selectedPhone.setmemorieRAM(valoareMemorieRAM);
              selectedPhone.setNrCamere(valoareNrCamere);
              selectedPhone.setMarimeBat(valoareMarimeBat);
              selectedPhone.setDiagonalaEcran(Float.parseFloat(textFieldDiagonalaEcran.getText()));
              telefoane[selectedIndex].setMarca(selectedPhone.getMarca());
              JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(saveButton);
              frame.dispose();
              updateTextAreaWithSelectedPhone(selectedPhone);
            }
        });
        panel.add(saveButton);
    }
        
        popup.add(panel);
        popup.setVisible(true);     
    }
    
    private void updateTextAreaWithSelectedPhone(Telefon selectedPhone) {
    jTextArea1.setText(selectedPhone.toString());
}
    
    private void ActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionListener
        // TODO add your handling code here:
    }//GEN-LAST:event_ActionListener

    private void ActionEvent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionEvent
       
    }//GEN-LAST:event_ActionEvent
    
    private void addLabelAndTextField(JPanel panel, String labelText, JTextField textField) {
    JLabel label = new JLabel(labelText);
    panel.add(label);
    panel.add(textField);
}
    
    private void initializareComboBox() {
        String[] numeTel = new String[telefoane.length];
        for(int i = 0; i < telefoane.length; i++) {
            String marca = telefoane[i].getMarca();
            String model = telefoane[i].getModel();
            numeTel[i] = marca + " " + model;
        }
        jComboBox1.setModel(new DefaultComboBoxModel<>(numeTel));
    }
    
    // Metoda pentru a adăuga ActionListener la combobox
    private void adaugaActionListenerComboBox() {
        jComboBox1.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e) {
                int selectedIndex = jComboBox1.getSelectedIndex();
                if(selectedIndex >= 0) {
                    Object obiectSelectat = telefoane[selectedIndex];
                    String textAfisat = obiectSelectat.toString();
                    jTextArea1.setText(textAfisat);
                    afisarePopUp(selectedIndex, telefoane);
                }
            }
        });
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telefoaneint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telefoaneint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telefoaneint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telefoaneint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telefoaneint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button backtest;
    private javax.swing.JMenuItem home;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenu menu;
    private javax.swing.JLabel titlu;
    // End of variables declaration//GEN-END:variables
}
