package newpackage;
import interfete.*;
import java.awt.*;
import javax.swing.*;
import com.mycompany.magazinelectronice.*;

/**
 *
 * @author Razvan
 */
public class InterfataGraficaMagazinElectronice extends javax.swing.JFrame {
    public InterfataGraficaMagazinElectronice() {
        initComponents();
         setLocationRelativeTo(null);
         setVisible(true);
         getContentPane().setBackground(new Color(173, 216, 230)); 
    setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlumagazin = new javax.swing.JLabel();
        autorinume = new javax.swing.JTextField();
        telefoanebut = new java.awt.Button();
        tabletabut = new java.awt.Button();
        desktopbut = new java.awt.Button();
        laptopbut = new java.awt.Button();
        smartwatchbut = new java.awt.Button();
        fitnessbut = new java.awt.Button();
        castibut = new java.awt.Button();
        boxeportbut = new java.awt.Button();
        cautPar = new java.awt.Button();
        jMenuBar1 = new javax.swing.JMenuBar();
        intclt = new javax.swing.JMenu();
        home = new javax.swing.JMenuItem();
        intang = new javax.swing.JMenu();
        ang = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.gray);

        titlumagazin.setBackground(new java.awt.Color(255, 255, 255));
        titlumagazin.setFont(new java.awt.Font("ISOCT2_IV25", 1, 36)); // NOI18N
        titlumagazin.setForeground(new java.awt.Color(255, 51, 51));
        titlumagazin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlumagazin.setText("Nemag");
        titlumagazin.setToolTipText("");

        autorinume.setEditable(false);
        autorinume.setBackground(new java.awt.Color(153, 153, 153));
        autorinume.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 18)); // NOI18N
        autorinume.setForeground(new java.awt.Color(255, 0, 0));
        autorinume.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        autorinume.setText("Proiect făcut de : Munteanu Georgian Valentin, Serea Alexandru, Slavu Emanuel, Tudor Alexandru - Răzvan");

        telefoanebut.setLabel("Telefoane");
        telefoanebut.setName(""); // NOI18N
        telefoanebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoanebutActionPerformed(evt);
            }
        });

        tabletabut.setLabel("Tableta");
        tabletabut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabletabutActionPerformed(evt);
            }
        });

        desktopbut.setLabel("Desktop");
        desktopbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desktopbutActionPerformed(evt);
            }
        });

        laptopbut.setLabel("Laptop");
        laptopbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laptopbutActionPerformed(evt);
            }
        });

        smartwatchbut.setLabel("Smart Watch");
        smartwatchbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smartwatchbutActionPerformed(evt);
            }
        });

        fitnessbut.setLabel("Fitness Band");
        fitnessbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fitnessbutActionPerformed(evt);
            }
        });

        castibut.setLabel("Casti");
        castibut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                castibutActionPerformed(evt);
            }
        });

        boxeportbut.setLabel("Boxe Portabile");
        boxeportbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxeportbutActionPerformed(evt);
            }
        });

        cautPar.setLabel("Cautare dupa parametrii");
        cautPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cautParActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        intclt.setText("Interfata Client");

        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        intclt.add(home);

        jMenuBar1.add(intclt);

        intang.setText("Interfata Angajat");

        ang.setText("Acces meniu angajati");
        ang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angActionPerformed(evt);
            }
        });
        intang.add(ang);

        jMenuBar1.add(intang);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titlumagazin, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(autorinume, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(smartwatchbut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telefoanebut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(laptopbut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(castibut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tabletabut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fitnessbut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(desktopbut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxeportbut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(cautPar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titlumagazin, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(autorinume, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(cautPar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(laptopbut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tabletabut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desktopbut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(telefoanebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(201, 201, 201)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(smartwatchbut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(castibut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxeportbut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fitnessbut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefoanebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoanebutActionPerformed
        this.setVisible(false);
        
        telefoaneint telint = new telefoaneint();
        telint.setVisible(true);
    }//GEN-LAST:event_telefoanebutActionPerformed

    private void tabletabutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabletabutActionPerformed
        this.setVisible(false);
        
        tabletaint tabint = new tabletaint();
        tabint.setVisible(true);
    }//GEN-LAST:event_tabletabutActionPerformed

    private void desktopbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desktopbutActionPerformed
        this.setVisible(false);
        
        desktopint deskint = new desktopint();
        deskint.setVisible(true);
    }//GEN-LAST:event_desktopbutActionPerformed

    private void laptopbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laptopbutActionPerformed
        this.setVisible(false);
        
        laptopint lapint = new laptopint();
        lapint.setVisible(true);
    }//GEN-LAST:event_laptopbutActionPerformed

    private void smartwatchbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smartwatchbutActionPerformed
        this.setVisible(false);
        
        smartint smint = new smartint();
        smint.setVisible(true);
    }//GEN-LAST:event_smartwatchbutActionPerformed

    private void fitnessbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fitnessbutActionPerformed
        this.setVisible(false);
        
        fitint fint = new fitint();
        fint.setVisible(true);
    }//GEN-LAST:event_fitnessbutActionPerformed

    private void castibutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_castibutActionPerformed
        this.setVisible(false);
        
        catiint casint = new catiint();
        casint.setVisible(true);
    }//GEN-LAST:event_castibutActionPerformed

    private void boxeportbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxeportbutActionPerformed
        this.setVisible(false);
        
        boxeint boxint = new boxeint();
        boxint.setVisible(true);
    }//GEN-LAST:event_boxeportbutActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        this.setVisible(false);
   
        InterfataGraficaMagazinElectronice home = new InterfataGraficaMagazinElectronice();
        home.setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void angActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angActionPerformed
        this.setVisible(false);
   
        interfataang angint = new interfataang();
        angint.setVisible(true);
    }//GEN-LAST:event_angActionPerformed

    private void cautParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cautParActionPerformed
        JDialog dialog = new JDialog(this, "Cautare", true);
    dialog.setLayout(new GridLayout(6, 2));

    JTextField textFieldMarca = new JTextField();
    JTextField textFieldModel = new JTextField();
    JTextField textFieldCantitate = new JTextField();
    JTextField textFieldAnAparitie = new JTextField();
    JTextField textFieldPret = new JTextField();

    addLabelAndTextField(dialog, "Marca:", textFieldMarca);
    addLabelAndTextField(dialog, "Model:", textFieldModel);
    addLabelAndTextField(dialog, "Cantitate:", textFieldCantitate);
    addLabelAndTextField(dialog, "An aparitie:", textFieldAnAparitie);
    addLabelAndTextField(dialog, "Pret:", textFieldPret);
    
    Instances instances = new Instances();
    Device[] instancesArray =  instances.getInstancesArray("instances");
    
    rezcautdupacond myFrame = new rezcautdupacond();
    StringBuilder resultBuilder = new StringBuilder();

    JButton searchButton = new JButton("Cauta");
    searchButton.addActionListener(event -> {
        String marca = textFieldMarca.getText().trim();
    String model = textFieldModel.getText().trim();
    String cantitateText = textFieldCantitate.getText().trim();
    String anAparitieText = textFieldAnAparitie.getText().trim();
    String pretText = textFieldPret.getText().trim();
 
    
   
    Device searchDevice = new Device();
    
    if (!marca.isEmpty()) {
        searchDevice.setMarca(marca);
    }
    
    if (!model.isEmpty()) {
    searchDevice.setModel(model);
    }
    
    int cantitate = 0;
    if (!cantitateText.isEmpty()) {
    try {
        cantitate = Integer.parseInt(cantitateText);
    } catch (NumberFormatException e) {       
        System.out.println("Introduceti un numar valid pentru cantitate.");
    }
    }
    searchDevice.setCantitate(cantitate);
    
    int anAparitie = 0;
    if (!anAparitieText.isEmpty()) {
    try {
        anAparitie = Integer.parseInt(anAparitieText);
    } catch (NumberFormatException e) {    
        System.out.println("Introduceti un numar valid pentru anul de aparitie.");
    }
    }
    searchDevice.setAnAparitie(anAparitie);
    
    if (!model.isEmpty()) {
    searchDevice.setModel(model);
    }
    float pret = 0.0f;
    if (!pretText.isEmpty()) {
    try {
        pret = Float.parseFloat(pretText);
    } catch (NumberFormatException e) {   
        System.out.println("Introduceti un numar valid pentru pret.");
    }
    }
    searchDevice.setPret(pret);
    for (Device instance : instancesArray) {
        boolean match = true; 

    
    if (!marca.isEmpty() && !instance.getMarca().equals(searchDevice.getMarca())) {
        match = false; 
    }

    if (!model.isEmpty() && !instance.getModel().equals(searchDevice.getModel())) {
        match = false;
    }
    
    if (searchDevice.getCantitate() != 0 && instance.getCantitate() != searchDevice.getCantitate()) {
        match = false; 
    }
    
    if (searchDevice.getAnAparitie() != 0 && instance.getAnAparitie() != searchDevice.getAnAparitie()) {
        match = false;
    }
    
    if (searchDevice.getPret() != 0.0f && instance.getPret() != searchDevice.getPret()) {
        match = false;
    }
    if (match) {
        String result = "Informațiile căutate: ..."; 
        myFrame.displaySearchResult(result);
        myFrame.displaySearchResult(resultBuilder.toString());
        myFrame.setVisible(true);
    }
    }
    });
    
    dialog.add(searchButton);
    
    dialog.setSize(400, 400);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
    }//GEN-LAST:event_cautParActionPerformed

    private void addLabelAndTextField(Container container, String labelText, JTextField textField) {
    JLabel label = new JLabel(labelText);
    container.add(label);
    container.add(textField);
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfataGraficaMagazinElectronice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfataGraficaMagazinElectronice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfataGraficaMagazinElectronice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfataGraficaMagazinElectronice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfataGraficaMagazinElectronice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ang;
    private javax.swing.JTextField autorinume;
    private java.awt.Button boxeportbut;
    private java.awt.Button castibut;
    private java.awt.Button cautPar;
    private java.awt.Button desktopbut;
    private java.awt.Button fitnessbut;
    private javax.swing.JMenuItem home;
    private javax.swing.JMenu intang;
    private javax.swing.JMenu intclt;
    private javax.swing.JMenuBar jMenuBar1;
    private java.awt.Button laptopbut;
    private java.awt.Button smartwatchbut;
    private java.awt.Button tabletabut;
    private java.awt.Button telefoanebut;
    private javax.swing.JLabel titlumagazin;
    // End of variables declaration//GEN-END:variables
}
